name: Main branch

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
    branches-ignore:
      - master

jobs:
  build:
    name: Lint and build website
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/jod
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build website
        run: npm run build
